# Generated by Django 4.2.4 on 2023-08-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('we', '0003_facebook_instagram_delete_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebook',
            old_name='full_name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='instagram',
            old_name='full_name',
            new_name='username',
        ),
    ]
